name: Build LO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-24.04 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        
        sudo apt-get install -y --no-install-recommends \
            git \
            build-essential \
            zip \
            nasm \
            python3 \
            python3-dev \
            autoconf \
            gperf \
            xsltproc \
            libxml2-utils \
            bison \
            flex \
            pkg-config \
            ccache \
            openssh-server \
            cmake \
            sudo \
            locales \
            libnss3

    - name: Configure
      run: |
        pwd
        ./scripts/setup
    - name: build
      run: |
        ls 
        cd scripts
        ./build
        ls 
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}